const projects=[
{id:1,name:"Parkside Apartments",city:"Frisco, TX",type:"Multifamily",stage:"Pre-construction",value:38000000,units:247,start:"Oct 2026",score:94,gc:"XYZ Construction",developer:"ABC Development",architect:"Smith & Associates",trade:["Siding","Windows","Doors"],lat:32.91,left:70,top:28,source:"Demo dataset"},
{id:2,name:"Northstar Logistics Center",city:"Fort Worth, TX",type:"Industrial",stage:"Active",value:12500000,units:null,start:"Aug 2026",score:87,gc:"Northstar Builders",developer:"Northstar Development",architect:"Ridge Studio",trade:["Roofing","HVAC","Electrical"],lat:32.80,left:30,top:55,source:"Demo dataset"},
{id:3,name:"Legacy Medical Office",city:"Plano, TX",type:"Commercial",stage:"Permit approved",value:7800000,units:null,start:"Nov 2026",score:82,gc:"Legacy GC",developer:"MedCore Properties",architect:"Apex Design",trade:["HVAC","Electrical","Flooring"],lat:33.02,left:48,top:38,source:"Demo dataset"},
{id:4,name:"Riverside Townhomes",city:"Arlington, TX",type:"Residential",stage:"Active",value:9200000,units:84,start:"Sep 2026",score:79,gc:"Riverside Construction",developer:"Oak Residential",architect:"Linework",trade:["Roofing","Siding","Flooring"],lat:32.74,left:58,top:68,source:"Demo dataset"},
{id:5,name:"Cedar Mixed-Use",city:"Dallas, TX",type:"Mixed-use",stage:"Planning",value:52000000,units:320,start:"Jan 2027",score:91,gc:"Cedar Build Group",developer:"Cedar Partners",architect:"Urban Form",trade:["Windows","Doors","Electrical"],lat:32.78,left:82,top:44,source:"Demo dataset"},
{id:6,name:"Mansfield Commerce Park",city:"Mansfield, TX",type:"Industrial",stage:"Pre-construction",value:18500000,units:null,start:"Dec 2026",score:85,gc:"MCP Contractors",developer:"Commerce Holdings",architect:"Westline",trade:["Roofing","HVAC","Electrical"],lat:32.56,left:22,top:76,source:"Demo dataset"}
];
let saved=JSON.parse(localStorage.getItem("buildscout_saved")||"[]");
let pipeline=JSON.parse(localStorage.getItem("buildscout_pipeline")||"{}");
let currentFilter="All", query="";
const app=document.getElementById("app");
function money(n){return n>=1e6?"$"+(n/1e6).toFixed(1)+"M":"$"+n.toLocaleString()}
function save(){localStorage.setItem("buildscout_saved",JSON.stringify(saved));localStorage.setItem("buildscout_pipeline",JSON.stringify(pipeline))}
function filtered(){return projects.filter(p=>(currentFilter==="All"||p.type===currentFilter||p.stage===currentFilter)&&(`${p.name} ${p.city} ${p.gc} ${p.developer}`.toLowerCase().includes(query.toLowerCase())))}
function projectCard(p){return `<div class="card project-card"><div class="score">${p.score}/100</div><span class="tag">${p.type}</span><span class="tag">${p.stage}</span><h2>${p.name}</h2><div class="muted">${p.city}</div><div class="stats"><div class="stat"><small>Estimated value</small><b>${money(p.value)}</b></div><div class="stat"><small>Units</small><b>${p.units||"—"}</b></div></div><div class="muted">Starts: ${p.start}</div><div class="row" style="margin-top:14px"><button class="btn primary" onclick="view(${p.id})">View project</button><button class="btn secondary" onclick="toggleSave(${p.id})">${saved.includes(p.id)?"Saved":"Save"}</button></div></div>`}
function map(){return `<div class="map"><div class="map-title">DFW • Demo construction intelligence</div><div class="road"></div>${filtered().map(p=>`<button class="pin" style="left:${p.left}%;top:${p.top}%" onclick="view(${p.id})" title="${p.name}"></button>`).join("")}</div>`}
function render(){app.innerHTML=`<div class="app"><header class="topbar"><div class="logo">BUILD<span>SCOUT</span></div><input class="search" placeholder="Search projects, companies, cities..." value="${query}" oninput="query=this.value;renderMain()"><div class="muted">Harrison ▾</div></header><div class="layout"><aside class="sidebar"><div class="nav"><button class="active" onclick="show('dashboard')">▦ Dashboard</button><button onclick="show('projects')">◉ Projects</button><button onclick="show('saved')">★ My Projects (${saved.length})</button><button onclick="show('pipeline')">▤ Sales Pipeline</button><button onclick="show('alerts')">♢ Alerts</button><button onclick="show('admin')">⚙ Admin</button></div><h3>Quick filters</h3><div class="filter">${["All","Multifamily","Commercial","Industrial","Residential","Mixed-use","Pre-construction","Active","Permit approved","Planning"].map(x=>`<button onclick="currentFilter='${x}';renderMain()">${x}</button>`).join("")}</div><div class="footer-note">Demo data only. Live public/licensed data connectors can be added next.</div></aside><main class="content" id="main"></main></div></div>`;renderMain()}
function renderMain(){const main=document.getElementById("main");let ps=filtered();main.innerHTML=`<div class="heading"><div><h1>Construction Intelligence</h1><div class="muted">Find projects before your competition.</div></div><button class="btn primary" onclick="show('projects')">Find opportunities</button></div>${map()}<div class="heading" style="margin-top:26px"><div><h2 style="margin:0">Top opportunities</h2><div class="muted">${ps.length} projects match your filters</div></div></div><div class="grid">${ps.map(projectCard).join("")||`<div class="empty">No projects match your search.</div>`}</div>`}
function show(page){currentFilter="All";query="";render();const main=document.getElementById("main");if(page==="projects")main.innerHTML=`<div class="heading"><div><h1>Projects</h1><div class="muted">Search and filter construction opportunities.</div></div></div><div class="grid">${projects.map(projectCard).join("")}</div>`;if(page==="saved")main.innerHTML=`<div class="heading"><div><h1>My Projects</h1><div class="muted">Saved opportunities for follow-up.</div></div></div><div class="grid">${projects.filter(p=>saved.includes(p.id)).map(projectCard).join("")||`<div class="empty">Save projects to build your prospect list.</div>`}</div>`;if(page==="pipeline")pipelinePage(main);if(page==="alerts")alertsPage(main);if(page==="admin")adminPage(main)}
function pipelinePage(main){const stages=["New Opportunity","Researching","Contacted","Quoted"];main.innerHTML=`<div class="heading"><div><h1>Sales Pipeline</h1><div class="muted">Track opportunities from discovery to close.</div></div></div><div class="pipeline">${stages.map(s=>`<div class="column"><h3>${s}</h3>${projects.filter(p=>(pipeline[p.id]||"New Opportunity")===s).map(p=>`<div class="lead"><b>${p.name}</b><div class="muted">${money(p.value)}</div><button class="btn secondary" style="margin-top:8px" onclick="advance(${p.id})">Advance →</button></div>`).join("")}</div>`).join("")}</div>`}
function alertsPage(main){main.innerHTML=`<div class="heading"><div><h1>Alerts</h1><div class="muted">New opportunities matching your territory and trades.</div></div></div><div class="card"><h2>🔔 Opportunity alerts</h2><p class="muted">Demo alert: A new multifamily project matching your profile has been detected.</p><button class="btn primary" onclick="alert('Alert preferences saved.')">Save alert preferences</button></div><div class="card" style="margin-top:16px"><h2>Recommended alert</h2><p><b>Multifamily • $10M+ • within 50 miles • Pre-construction</b></p><p class="muted">This configuration is designed to surface projects early enough for sales outreach.</p></div>`}
function adminPage(main){main.innerHTML=`<div class="heading"><div><h1>Admin Dashboard</h1><div class="muted">MVP controls and data-source health.</div></div></div><div class="grid"><div class="card"><h2>Projects</h2><h1>${projects.length}</h1><div class="muted">Demo projects</div></div><div class="card"><h2>Saved</h2><h1>${saved.length}</h1><div class="muted">User saves</div></div><div class="card"><h2>Data source</h2><h3 style="color:#8fe0ad">● Demo dataset healthy</h3><div class="muted">Live municipal/licensed connectors not yet enabled.</div></div></div>`}
function view(id){const p=projects.find(x=>x.id===id);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><span class="tag">${p.type}</span><span class="tag">${p.stage}</span><h1>${p.name}</h1><div class="muted">${p.city}</div><div class="stats"><div class="stat"><small>Estimated value</small><b>${money(p.value)}</b></div><div class="stat"><small>Units</small><b>${p.units||"N/A"}</b></div><div class="stat"><small>Expected start</small><b>${p.start}</b></div><div class="stat"><small>Opportunity score</small><b>${p.score}/100</b></div></div><div class="card"><h2>Why this is an opportunity</h2><p>✓ Project size matches a commercial sales opportunity</p><p>✓ Construction stage allows early outreach</p><p>✓ Location is within the DFW launch market</p><p>✓ Trade matches can be layered into the scoring engine</p></div><div class="card" style="margin-top:14px"><h2>Project team</h2><p><b>Developer:</b> ${p.developer}</p><p><b>General contractor:</b> ${p.gc}</p><p><b>Architect:</b> ${p.architect}</p></div><div class="card" style="margin-top:14px"><h2>Matched trades</h2><p>${p.trade.map(t=>`<span class="tag">${t}</span>`).join("")}</p><p class="muted">Source: ${p.source} • Last verified: demo</p></div><div class="row"><button class="btn primary" onclick="toggleSave(${p.id});document.getElementById('modal').remove()">Save project</button><button class="btn secondary" onclick="addPipeline(${p.id});document.getElementById('modal').remove()">Add to pipeline</button></div></div></div>`)}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];save();render()}
function addPipeline(id){pipeline[id]="New Opportunity";save();show("pipeline")}
function advance(id){const stages=["New Opportunity","Researching","Contacted","Quoted"];let i=stages.indexOf(pipeline[id]||stages[0]);pipeline[id]=stages[Math.min(i+1,stages.length-1)];save();show("pipeline")}
render();
