window.BUILDSCOUT_DEMO_PROJECTS = [
  {
    "id": "demo-1",
    "name": "North Apartments 1",
    "city": "Dallas, TX",
    "lat": 32.797831,
    "lon": -96.856859,
    "type": "Multifamily",
    "stage": "Planning",
    "value": 12800000,
    "units": 180,
    "start": "Q1 2027",
    "score": 84,
    "developer": "Riverside Development",
    "gc": "Metro Construction Group",
    "architect": "Oak Design Studio",
    "trade": [
      "Roofing",
      "Siding"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261000"
  },
  {
    "id": "demo-2",
    "name": "Cedar Commerce Center 2",
    "city": "Fort Worth, TX",
    "lat": 32.76709,
    "lon": -97.273441,
    "type": "Commercial",
    "stage": "Permit approved",
    "value": 9200000,
    "units": null,
    "start": "Oct 2026",
    "score": 83,
    "developer": "Park Development",
    "gc": "Trinity Construction Group",
    "architect": "Summit Design Studio",
    "trade": [
      "HVAC",
      "Electrical"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261001"
  },
  {
    "id": "demo-3",
    "name": "Legacy Logistics Park 3",
    "city": "Arlington, TX",
    "lat": 32.72641,
    "lon": -97.16832,
    "type": "Industrial",
    "stage": "Pre-construction",
    "value": 6500000,
    "units": null,
    "start": "Sep 2026",
    "score": 74,
    "developer": "Metro Development",
    "gc": "Oak Construction Group",
    "architect": "Pioneer Design Studio",
    "trade": [
      "Windows",
      "Doors"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261002"
  },
  {
    "id": "demo-4",
    "name": "Riverside District 4",
    "city": "Plano, TX",
    "lat": 33.065559,
    "lon": -96.751568,
    "type": "Mixed-use",
    "stage": "Active",
    "value": 52000000,
    "units": 310,
    "start": "Oct 2026",
    "score": 73,
    "developer": "Trinity Development",
    "gc": "Summit Construction Group",
    "architect": "Lone Star Design Studio",
    "trade": [
      "Flooring",
      "Drywall"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261003"
  },
  {
    "id": "demo-5",
    "name": "Park Townhomes 5",
    "city": "Frisco, TX",
    "lat": 33.162676,
    "lon": -96.886657,
    "type": "Residential",
    "stage": "Planning",
    "value": 6500000,
    "units": 420,
    "start": "Oct 2026",
    "score": 90,
    "developer": "Oak Development",
    "gc": "Pioneer Construction Group",
    "architect": "Foundry Design Studio",
    "trade": [
      "Concrete",
      "Framing"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261004"
  },
  {
    "id": "demo-6",
    "name": "Metro Apartments 6",
    "city": "McKinney, TX",
    "lat": 33.185879,
    "lon": -96.634104,
    "type": "Multifamily",
    "stage": "Permit approved",
    "value": 12800000,
    "units": 84,
    "start": "Q1 2027",
    "score": 81,
    "developer": "Summit Development",
    "gc": "Lone Star Construction Group",
    "architect": "North Design Studio",
    "trade": [
      "Roofing",
      "Siding"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261005"
  },
  {
    "id": "demo-7",
    "name": "Trinity Commerce Center 7",
    "city": "Irving, TX",
    "lat": 32.858258,
    "lon": -96.993598,
    "type": "Commercial",
    "stage": "Pre-construction",
    "value": 27000000,
    "units": null,
    "start": "Q1 2027",
    "score": 89,
    "developer": "Pioneer Development",
    "gc": "Foundry Construction Group",
    "architect": "Cedar Design Studio",
    "trade": [
      "HVAC",
      "Electrical"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261006"
  },
  {
    "id": "demo-8",
    "name": "Oak Logistics Park 8",
    "city": "Grand Prairie, TX",
    "lat": 32.68954,
    "lon": -96.968104,
    "type": "Industrial",
    "stage": "Active",
    "value": 18500000,
    "units": null,
    "start": "Q1 2027",
    "score": 83,
    "developer": "Lone Star Development",
    "gc": "North Construction Group",
    "architect": "Legacy Design Studio",
    "trade": [
      "Windows",
      "Doors"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261007"
  },
  {
    "id": "demo-9",
    "name": "Summit District 9",
    "city": "Mansfield, TX",
    "lat": 32.588456,
    "lon": -97.151837,
    "type": "Mixed-use",
    "stage": "Planning",
    "value": 18500000,
    "units": 84,
    "start": "Nov 2026",
    "score": 87,
    "developer": "Foundry Development",
    "gc": "Cedar Construction Group",
    "architect": "Riverside Design Studio",
    "trade": [
      "Flooring",
      "Drywall"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261008"
  },
  {
    "id": "demo-10",
    "name": "Pioneer Townhomes 10",
    "city": "Grapevine, TX",
    "lat": 32.906267,
    "lon": -97.036887,
    "type": "Residential",
    "stage": "Permit approved",
    "value": 76000000,
    "units": 220,
    "start": "Oct 2026",
    "score": 83,
    "developer": "North Development",
    "gc": "Legacy Construction Group",
    "architect": "Park Design Studio",
    "trade": [
      "Concrete",
      "Framing"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261009"
  },
  {
    "id": "demo-11",
    "name": "Lone Star Apartments 11",
    "city": "Lewisville, TX",
    "lat": 33.045516,
    "lon": -97.016113,
    "type": "Multifamily",
    "stage": "Pre-construction",
    "value": 27000000,
    "units": 84,
    "start": "Dec 2026",
    "score": 88,
    "developer": "Cedar Development",
    "gc": "Riverside Construction Group",
    "architect": "Metro Design Studio",
    "trade": [
      "Roofing",
      "Siding"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261010"
  },
  {
    "id": "demo-12",
    "name": "Foundry Commerce Center 12",
    "city": "Denton, TX",
    "lat": 33.282024,
    "lon": -97.186571,
    "type": "Commercial",
    "stage": "Active",
    "value": 27000000,
    "units": null,
    "start": "Dec 2026",
    "score": 91,
    "developer": "Legacy Development",
    "gc": "Park Construction Group",
    "architect": "Trinity Design Studio",
    "trade": [
      "HVAC",
      "Electrical"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261011"
  },
  {
    "id": "demo-13",
    "name": "North Logistics Park 13",
    "city": "Dallas, TX",
    "lat": 32.754588,
    "lon": -96.736342,
    "type": "Industrial",
    "stage": "Planning",
    "value": 12800000,
    "units": null,
    "start": "Dec 2026",
    "score": 96,
    "developer": "Riverside Development",
    "gc": "Metro Construction Group",
    "architect": "Oak Design Studio",
    "trade": [
      "Windows",
      "Doors"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261012"
  },
  {
    "id": "demo-14",
    "name": "Cedar District 14",
    "city": "Fort Worth, TX",
    "lat": 32.763631,
    "lon": -97.290327,
    "type": "Mixed-use",
    "stage": "Permit approved",
    "value": 9200000,
    "units": 84,
    "start": "Nov 2026",
    "score": 96,
    "developer": "Park Development",
    "gc": "Trinity Construction Group",
    "architect": "Summit Design Studio",
    "trade": [
      "Flooring",
      "Drywall"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261013"
  },
  {
    "id": "demo-15",
    "name": "Legacy Townhomes 15",
    "city": "Arlington, TX",
    "lat": 32.735234,
    "lon": -97.066535,
    "type": "Residential",
    "stage": "Pre-construction",
    "value": 38500000,
    "units": 180,
    "start": "Sep 2026",
    "score": 91,
    "developer": "Metro Development",
    "gc": "Oak Construction Group",
    "architect": "Pioneer Design Studio",
    "trade": [
      "Concrete",
      "Framing"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261014"
  },
  {
    "id": "demo-16",
    "name": "Riverside Apartments 16",
    "city": "Plano, TX",
    "lat": 33.047386,
    "lon": -96.7598,
    "type": "Multifamily",
    "stage": "Active",
    "value": 27000000,
    "units": 84,
    "start": "Nov 2026",
    "score": 87,
    "developer": "Trinity Development",
    "gc": "Summit Construction Group",
    "architect": "Lone Star Design Studio",
    "trade": [
      "Roofing",
      "Siding"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261015"
  },
  {
    "id": "demo-17",
    "name": "Park Commerce Center 17",
    "city": "Frisco, TX",
    "lat": 33.181028,
    "lon": -96.769414,
    "type": "Commercial",
    "stage": "Planning",
    "value": 76000000,
    "units": null,
    "start": "Nov 2026",
    "score": 81,
    "developer": "Oak Development",
    "gc": "Pioneer Construction Group",
    "architect": "Foundry Design Studio",
    "trade": [
      "HVAC",
      "Electrical"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261016"
  },
  {
    "id": "demo-18",
    "name": "Metro Logistics Park 18",
    "city": "McKinney, TX",
    "lat": 33.176965,
    "lon": -96.624271,
    "type": "Industrial",
    "stage": "Permit approved",
    "value": 6500000,
    "units": null,
    "start": "Dec 2026",
    "score": 86,
    "developer": "Summit Development",
    "gc": "Lone Star Construction Group",
    "architect": "North Design Studio",
    "trade": [
      "Windows",
      "Doors"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261017"
  },
  {
    "id": "demo-19",
    "name": "Trinity District 19",
    "city": "Irving, TX",
    "lat": 32.78424,
    "lon": -96.915529,
    "type": "Mixed-use",
    "stage": "Pre-construction",
    "value": 18500000,
    "units": 84,
    "start": "Dec 2026",
    "score": 96,
    "developer": "Pioneer Development",
    "gc": "Foundry Construction Group",
    "architect": "Cedar Design Studio",
    "trade": [
      "Flooring",
      "Drywall"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261018"
  },
  {
    "id": "demo-20",
    "name": "Oak Townhomes 20",
    "city": "Grand Prairie, TX",
    "lat": 32.699191,
    "lon": -97.01157,
    "type": "Residential",
    "stage": "Active",
    "value": 76000000,
    "units": 220,
    "start": "Nov 2026",
    "score": 74,
    "developer": "Lone Star Development",
    "gc": "North Construction Group",
    "architect": "Legacy Design Studio",
    "trade": [
      "Concrete",
      "Framing"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261019"
  },
  {
    "id": "demo-21",
    "name": "Summit Apartments 21",
    "city": "Mansfield, TX",
    "lat": 32.532179,
    "lon": -97.153558,
    "type": "Multifamily",
    "stage": "Planning",
    "value": 52000000,
    "units": 126,
    "start": "Nov 2026",
    "score": 89,
    "developer": "Foundry Development",
    "gc": "Cedar Construction Group",
    "architect": "Riverside Design Studio",
    "trade": [
      "Roofing",
      "Siding"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261020"
  },
  {
    "id": "demo-22",
    "name": "Pioneer Commerce Center 22",
    "city": "Grapevine, TX",
    "lat": 32.885429,
    "lon": -97.12343,
    "type": "Commercial",
    "stage": "Permit approved",
    "value": 52000000,
    "units": null,
    "start": "Oct 2026",
    "score": 79,
    "developer": "North Development",
    "gc": "Legacy Construction Group",
    "architect": "Park Design Studio",
    "trade": [
      "HVAC",
      "Electrical"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261021"
  },
  {
    "id": "demo-23",
    "name": "Lone Star Logistics Park 23",
    "city": "Lewisville, TX",
    "lat": 33.044095,
    "lon": -96.981723,
    "type": "Industrial",
    "stage": "Pre-construction",
    "value": 18500000,
    "units": null,
    "start": "Nov 2026",
    "score": 72,
    "developer": "Cedar Development",
    "gc": "Riverside Construction Group",
    "architect": "Metro Design Studio",
    "trade": [
      "Windows",
      "Doors"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261022"
  },
  {
    "id": "demo-24",
    "name": "Foundry District 24",
    "city": "Denton, TX",
    "lat": 33.203453,
    "lon": -97.151404,
    "type": "Mixed-use",
    "stage": "Active",
    "value": 6500000,
    "units": 180,
    "start": "Q1 2027",
    "score": 76,
    "developer": "Legacy Development",
    "gc": "Park Construction Group",
    "architect": "Trinity Design Studio",
    "trade": [
      "Flooring",
      "Drywall"
    ],
    "source": "BuildScout demo data",
    "source_url": "",
    "verified": "Demo only",
    "permit_number": "DEMO-20261023"
  }
];
